name: Build, test and analyze by sonar
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-scan:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Sonar Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore DataIngestorService.slnx

      - name: Begin Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"fjord-code_DataIngestorService" \
            /o:"snow-flake" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.cobertura.reportsPaths="coverage.xml"

      - name: Build
        run: dotnet build DataIngestorService.slnx --no-restore --configuration Release

      - name: Run All Tests
        run: |
          dotnet test DataIngestorService.slnx --no-build --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory coverage

      - name: Combine Coverage Reports
        run: find coverage -name "coverage.cobertura.xml" -exec cp {} coverage.xml \;

      - name: End Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"